config/routes.rb
Rails.application.routes.draw do
  resources :search, only: [:index, :show]

  root 'search#home'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/image.rb
class Image
  include ActiveModel::Model
  attr_accessor :id, :title, :username, :date_taken, :image_url

  def self.find_by(id:)
    info = flickr.photos.getInfo(photo_id: id)
    new(id: id, title: info.title, username: info.owner.username, image_url: FlickRaw.url_z(info), date_taken: info.dates.taken)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  before_action :redirect_if_blank, only: [:index]

  def home
    @form = SearchForm.new
  end

  def index
    @form = SearchForm.new(params[:search_form])
    @images = @form.results
  end

  def show
    @image = Image.find_by(id: params[:id])
  end

  private

  def redirect_if_blank
    if params[:search_form][:search].blank?
      # flash[:error] = "Cannot search empty field"
      redirect_to root_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.slim
doctype html
html
  head
    title FlickrSearch
    = csrf_meta_tags
    = action_cable_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track' => 'reload'
  body class="c-#{controller_name} a-#{controller.action_name}"
    = render 'layouts/modules/navbar'
    = yield

app/views/layouts/modules/_navbar.html.slim
nav.navbar.navbar-default.main-nav
  .container
    .navbar-header
      button.navbar-toggle.collapsed data-toggle='collapse' data-target='#navigation-collapsable' aria-expanded='false'
        span.sr-only Toggle Nagivation
        span.icon-bar
        span.icon-bar
        span.icon-bar
      = link_to 'Flickr Search', root_path, class: 'navbar-brand'

app/views/search/home.html.slim
.jumbotron.search-bar
  .container
    .row
      .col-md-8.col-md-offset-2.text-center
        h2 Search for Flickr Photos without signing in!
    .row
      .col-md-8.col-md-offset-2
        = simple_form_for @form, url: search_index_path, method: :get do |f|
          .row
            .col-md-10
              = f.input :search, label: false
            .col-md-2
              = f.submit 'Search', class: 'btn btn-default btn-lg'

app/views/search/index.html.slim
.container
  .row
    .col-md-12
      .row.masonry-container
        - @images.each_with_index do |image, index|
          .col-sm-12.col-md-4.box
            .thumbnail
              = image_tag image.image_url, class: 'img-responsive'
              .caption
                h4 = link_to image.title, search_path(id: image.id)
                dl.dl-horizontal
                  dt Posted by
                  dd = image.username
                  dt Date taken: 
                  dd = image.date_taken

app/views/search/show.html.slim
.container
  .row
    .col-md-8
      = image_tag @image.image_url, class: 'img-responsive'
    .col-md-4
      .panel.panel-default
        .panel-heading Taken by #{@image.username}
        .panel-body
          dl
            dt Title
            dd = @image.title
            dt Date Taken
            dd = @image.date_taken